### ISSUE TITLE
Sidebar Profile not loading

### ISSUE THREAD

**Issue by PhineasBubbles** [mvarela/orbit-cv#7] opened 2020-11-12 01:19 UTC
Using Miktex and Texmaker. Compiled using LuaLaTex as XeLaTex has some kind of issue loading the \fa icons (XeLaTex also does not load the sidebar profile).

![texmaker_2020-11-12_11-44-35](https://user-images.githubusercontent.com/74333443/98882614-9a982780-24dc-11eb-95e9-e28d8883d44d.png)

I assume it has somethign to do with the install of Miktex and Texmaker as they were previously working, however I reinstalled both and now the sidebar info is missing. Other files compile as intended. Same issue occurs with Texstudio.

**Log**
[orbit-cv.log](https://github.com/mvarela/orbit-cv/files/5527647/orbit-cv.log)

**Comment by mvarela** [comment] 2020-11-12 04:01
Hi,
  I'm afraid I can't reproduce this issue. I've run both `xelatex` and `lualatex` on the demo file, and they both generate the correct output. Are you sure you have FontAwesome and Roboto installed correctly? Also, did you try this on a fresh version of the example file, or had you modified anything?

**Comment by PhineasBubbles** [comment] 2020-11-12 04:23
Hey,

I know there are some warnings due to not having some fonts. If I understand it right it is due to not having a bold and/or italic version of Roboto Light? I downloaded them from [Google Fonts](https://fonts.google.com/specimen/Roboto) and there doesn't seem to be a bold version. I have tried reinstalling the roboto fonts but doesn't seem to make a difference. 

This was done on a fresh version of the example file.

EDIT: Compiled fine using another laptop but the same file. The laptop has Miktex 2.9 installed. My computer has the latest version.
Unsure why the laptop version has 2 Miktex's installed but the PC version is the latest.

**PC Version**
![explorer_2020-11-12_15-04-49](https://user-images.githubusercontent.com/74333443/98896244-70ecf980-24f8-11eb-8eb8-1b92d72da5d6.png)
 
**Laptop Version**
![image](https://user-images.githubusercontent.com/74333443/98896367-aeea1d80-24f8-11eb-8c08-eba8195f0205.png)

**Comment by mvarela** [comment] 2020-11-12 04:42
I believe if you installed all OTF files (or TTFs, it shouldn't really matter) that you have downloaded from google fonts, it should work.  You can check that you have installed all the fonts referenced in the `.cls` file, maybe. 

I don't have access to a windows machine at the moment, so I can only try with TeXLive (under Linux or Mac). There maybe something in your install that is causing this issue...
From the log, I can't immediately tell what it is, though, but I'd suspect it is related to fonts, if you are using the stock example.

**Comment by PhineasBubbles** [comment] 2020-11-12 04:43
Sorry I have edited my comment as I have successfully compiled it using an older version of MiKTeX but unsure how to resolve the issue for my PC.

**Comment by mvarela** [comment] 2020-11-12 04:46
Ok, if you managed to compile it with an older version, then at least we can narrow it down to the install.
For reference, here's what I'm running:
```
XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/Arch Linux)
kpathsea version 6.3.2
Copyright 2020 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 67.1; using 67.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.2; using 2.10.4
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.7.2; using 2.7.2
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with poppler version 20.10.0
Compiled with fontconfig version 2.13.91; using 2.13.91
```
And for LuaLaTeX:
```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux)

Execute  'luahbtex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2020 Taco Hoekwater and the LuaTeX Team.
```

```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux)

The LuaTeX team is Hans Hagen, Hartmut Henkel, Taco Hoekwater, Luigi Scarso.

LuaHBTeX merges and builds upon (parts of) the code from these projects:

tex       : Donald Knuth
etex      : Peter Breitenlohner, Phil Taylor and friends
omega     : John Plaice and Yannis Haralambous
aleph     : Giuseppe Bilotta
pdftex    : Han The Thanh and friends
kpathsea  : Karl Berry, Olaf Weber and others
lua       : Roberto Ierusalimschy, Waldemar Celes and Luiz Henrique de Figueiredo
metapost  : John Hobby, Taco Hoekwater, Luigi Scarso, Hans Hagen and friends
pplib     : Paweł Jackowski
fontforge : George Williams (partial)
luajit    : Mike Pall (used in LuajitTeX)

Compiled with libharfbuzz 2.7.2; using 2.7.2
Compiled with libpng 1.6.37; using 1.6.37
Compiled with lua version 5.3.5
Compiled with mplib version 2.00
Compiled with zlib 1.2.11; using 1.2.11

Development id: 7306

```

**Comment by PhineasBubbles** [comment] 2020-11-12 04:53
Looks like I am using the same versions (I believe)

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 20.11) (preloaded format=xelatex 2020.11.12) 12 NOV 2020 15:18
entering extended mode
```

`This is LuaHBTeX, Version 1.12.0 (MiKTeX 20.11) (format=lualatex 2020.11.12) 12 NOV 2020 15:17
`

This looks to be a MiKTeX problem. It compiles using MiKTeX 20.7 (on my laptop). Not too sure how to get the other compiled information. I will be away for a bit so I will respond later.

**Comment by mvarela** [comment] 2020-11-12 12:14
I'll close this issue since it's related to MiKTeX itself (or your particular install). Let me know if you need further help!

**Comment by agravgaard** [comment] 2021-03-08 17:17
I'm having the same issue on Manjaro using both lualatex and xelatex (both directly and latexmk).
I'm using almost the exact same package versions and tex versions as you:
```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux)

The LuaTeX team is Hans Hagen, Hartmut Henkel, Taco Hoekwater, Luigi Scarso.

LuaHBTeX merges and builds upon (parts of) the code from these projects:

tex       : Donald Knuth
etex      : Peter Breitenlohner, Phil Taylor and friends
omega     : John Plaice and Yannis Haralambous
aleph     : Giuseppe Bilotta
pdftex    : Han The Thanh and friends
kpathsea  : Karl Berry, Olaf Weber and others
lua       : Roberto Ierusalimschy, Waldemar Celes and Luiz Henrique de Figueiredo
metapost  : John Hobby, Taco Hoekwater, Luigi Scarso, Hans Hagen and friends
pplib     : Paweł Jackowski
fontforge : George Williams (partial)
luajit    : Mike Pall (used in LuajitTeX)

Compiled with libharfbuzz 2.7.4; using 2.7.4
Compiled with libpng 1.6.37; using 1.6.37
Compiled with lua version 5.3.5
Compiled with mplib version 2.00
Compiled with zlib 1.2.11; using 1.2.11

Development id: 7306
```
I've tried updating to fontawesome5 and pointing setmainfont to the specific italic, bold and bolditalic fonts, but no luck...

The problem is reproducible with docker image aergus/latex (CI pipeline of [my gitlab repo](gitlab.com/agravgaard/resume).

**Comment by mvarela** [comment] 2021-03-08 19:27
I can now reproduce it (also on Manjaro), so there might be some update that broke this. I'll have a look soon-ish (pretty busy atm), but PRs are welcome if you have the time.

**Comment by agravgaard** [comment] 2021-03-09 21:49
I think I found the solution - `atbegshi`'s `\AtBeginShipoutFirst{}` seems broken, maybe due to some change in `tikz` 

I've added a pull-request #8

**Comment by mvarela** [comment] 2021-03-10 15:02
Thanks for the PR! I have just tried your branch, but it is still generating the empty sidebar... I tried it both with XeLaTeX and LuaTeX. Did you manage to build it correctly?.

```
XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/Arch Linux)
kpathsea version 6.3.2
Copyright 2020 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 68.2; using 68.2
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.4; using 2.10.4
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.7.4; using 2.7.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with poppler version 21.02.0
Compiled with fontconfig version 2.13.91; using 2.13.91
```

```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/Arch Linux)

The LuaTeX team is Hans Hagen, Hartmut Henkel, Taco Hoekwater, Luigi Scarso.

LuaHBTeX merges and builds upon (parts of) the code from these projects:

tex       : Donald Knuth
etex      : Peter Breitenlohner, Phil Taylor and friends
omega     : John Plaice and Yannis Haralambous
aleph     : Giuseppe Bilotta
pdftex    : Han The Thanh and friends
kpathsea  : Karl Berry, Olaf Weber and others
lua       : Roberto Ierusalimschy, Waldemar Celes and Luiz Henrique de Figueiredo
metapost  : John Hobby, Taco Hoekwater, Luigi Scarso, Hans Hagen and friends
pplib     : Paweł Jackowski
fontforge : George Williams (partial)
luajit    : Mike Pall (used in LuajitTeX)

Compiled with libharfbuzz 2.7.4; using 2.7.4
Compiled with libpng 1.6.37; using 1.6.37
Compiled with lua version 5.3.5
Compiled with mplib version 2.00
Compiled with zlib 1.2.11; using 1.2.11
```

**Comment by agravgaard** [comment] 2021-03-10 18:32
It _just works_ for me now. I tried again with latexmk, xelatex and lualatex - All of them produced the pdf with the proper sidebar as expected. (With the exception that xelatex doesn't display the FontAwesome symbols, but the text, image and links still work)

The only difference I can spot in version numbers is that I have `poppler version 21.03.0` instead, in the `xelatex --version` output.

**Comment by mvarela** [comment] 2021-03-10 19:25
My bad, I was on the wrong branch... :facepalm: 
It is working ok, I'll merge this.
Thanks a lot!

**Closed as completed** 2021-03-10 19:25 UTC
